Introduce a metrics yaml config file
gdvalle/trafficserver_exporter pull request #18
Opened 2019-05-06 09:57 UTC by jvgutierrez

Currently a commit is needed to add a new metric. A lot of them can be set using a config file instead of programmatically.

This avoids the requirement of releasing a new trafficserver_exporter version every time a new metric needs to be added

2019-05-08 10:36 UTC, jvgutierrez commented
@gdvalle any thoughts regarding this PR?

2019-05-08 22:53 UTC, gdvalle commented
Thanks @jvgutierrez!  I should have some time this weekend to give it a spin.

A couple quick thoughts though:

I did have some preference to keep the runtime dependencies minimal.  Packaging up a YAML file and requiring PyYAML could be a small burden when I'm not sure how many folks use custom metrics.  It'd be best if those could be contributed upstream.

Also noticed there's no inclusion for the config in the packaging (which, unfortunately, I've neglected thus far to put on PyPI), so it could mean a change in deployment for existing users as well.

On the positive side this cleans up a lot of repetitive code that was basically unchanged from the PoC :-)  Thanks for taking care of that!

2019-05-09 06:05 UTC, jvgutierrez commented
It's not only about custom metrics.. but being able to send different metrics for different instances of ATS running on the same server.

Regarding YAML, I've chosen this format instead of JSON because it supports comments. I'd be happy to offer support for both formats and make the yaml requirement optional if you consider that a strong requirement to get this merged.

2019-05-13 05:01 UTC, gdvalle commented
I don't think the YAML dependency is worth worrying about.  JSON would certainly keep requirements a little leaner, but I agree, the ergonomics of YAML is preferred.

I'd like to preserve the ability to run the package without providing a path to the metrics file.  Could we do something like this?

```diff --git a/setup.py b/setup.py
index db7e57c..8cb1db9 100644
--- a/setup.py
+++ b/setup.py
@@ -24,7 +24,9 @@ setup(
             'trafficserver_exporter=trafficserver_exporter.__main__:main'
         ],
     },
-    data_files=('metrics.yaml',),
+    package_data={
+        'trafficserver_exporter': ['metrics.yaml'],
+    },
     install_requires=[
         'prometheus_client>=0.0.11',
         'pyyaml>=3.12',
diff --git a/trafficserver_exporter/trafficserver_exporter.py b/trafficserver_exporter/trafficserver_exporter.py
index a775236..03c5454 100644
--- a/trafficserver_exporter/trafficserver_exporter.py
+++ b/trafficserver_exporter/trafficserver_exporter.py
@@ -3,12 +3,16 @@
 import argparse
 import logging
 
+from os import path
+
 from prometheus_client import REGISTRY, ProcessCollector
 
 from .collector import StatsPluginCollector
 from .http import start_http_server
 
 
+PKG_DIR = path.abspath(path.dirname(path.realpath(__file__)))
+
 ARGS = argparse.ArgumentParser(
     formatter_class=argparse.ArgumentDefaultsHelpFormatter,
     description="Traffic Server exporter for Prometheus",
@@ -22,6 +26,7 @@ ARGS.add_argument(
 ARGS.add_argument(
     "--metricsfile",
     dest="metricsfile",
+    default=path.join(PKG_DIR, "metrics.yaml"),
     help="YAML file containing the metrics definition",
 )
 ARGS.add_argument(
```

I also thought we could just call it `--metrics-file` and `metrics_file` respectively.

Thanks for being patent.  I think this looks great!

2019-05-13 07:53 UTC, jvgutierrez commented
Thanks for your review @gdvalle, I've implemented the requested changes.

note that I've used the standard library module pkgutil to get the metrics.yaml path instead of using os.path.

2019-05-13 13:57 UTC, gdvalle requested changes
The `metrics.yaml` file needs to be moved into the package dir now.

Otherwise, this LGTM.

2019-05-13 14:20 UTC, jvgutierrez commented
right, I've misinterpreted `pkgutil.get_data` function, so I've replaced it with:
```
PKG_METRICS_FILE = path.join(path.dirname(sys.modules['trafficserver_exporter'].__file__), 'metrics.yaml')
```
that's how the path is determined within `pkgutil.get_data`

2019-05-14 00:02 UTC, gdvalle approved these changes
Thanks!  I'll get this merged and bump a release.

2019-05-14 00:02 UTC, merged